### ISSUE TITLE
Issue when adjusting the base html font size

### ISSUE THREAD

**Issue by sethwhitaker** [twbs/rfs#102]
In previous versions of BS before this RFS was added, I often liked to set the `html{ font size:62.5% }`  which made the base font size 10px and all the rem calculations were much easier to calculate as everything was base 10 vs base 16.

Now when trying this same trick with the responsive typography turned on, the fonts using RFS all get bigger initially when it hits the 1200 breakpoint before scaling down. They end up scaling down proportionally from that larger size rather than the size I have set. I figure it has something to do with the html element font size adjustment but cant quite figure out why.

Is this trick not supported anymore with this technique or will it require some different configuration with the variables?  Ive been trying all sorts of different things with the `$rfs-base-font-size` & `$rsf-factor` variables to no avial.

**Comment by sethwhitaker** [comment]
I get that it changes the value of rem, but why does it cause the fonts to jump to a larger size when i cross over the 1200 breakpoint from >1200. Is this system entirely dependent on the base rem being equal to 16px? Couldnt you add another variable to offset the base html font size?

**Comment by MartijnCuppens** [comment]
> Why does it cause the fonts to jump to a larger size when i cross over the 1200 breakpoint from >1200. Is this system entirely dependent on the base rem being equal to 16px?

Yes.

> Couldnt you add another variable to offset the base html font size?

I think you can change `$rfs-rem-value` to `10` but I haven't tested this. 
https://github.com/twbs/rfs/blob/b7104cef13a028c7d240e640925b94aa8421470a/scss.scss#L32-L33

**Comment by sethwhitaker** [comment]
Ah Ha! That Seemed to have worked! I overlooked that variable in the scss file and you didnt have it documented.  Thanks for pointing that out!

The full trick requires this configuration

```scss
// Sets the base to 20px same as the default 1.25 when the base rem is 16px
$rfs-base-font-size: 2rem; 
// Fixes the base rem value in the calculations to match changed html value
$rfs-rem-value: 10; 

html { 62.5% }
```
