### ISSUE TITLE
Make use of the css `min()` function

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/rfs#110]
Hopefully one day the [`min()`](https://developer.mozilla.org/en-US/docs/Web/CSS/min) function will be implemented by all major browsers and that could simplify RFS a lot. 

For example:
```scss
.title {
  @include font-size(4rem);
}
```
would generate:
```css
.title {
  font-size: min(4rem, calc(1.525rem + 3.3vw));
}
```

I'm not planning to start developing this because currently no browser officially supports it, but this could be pretty cool. If anyone has any news about browsers starting to implement it, feel free to drop it here.

Currently Safari kind of supports `min()`, but it's still not perfect when resizing without the safari iframe hack (https://github.com/twbs/rfs/issues/14): https://codepen.io/MartijnCuppens/pen/ywaJpW

**Comment by benabraham** [comment]
Firefox already supports this https://caniuse.com/#feat=css-math-functions

**Comment by MartijnCuppens** [comment]
For the early adapters out here, you can now install this implementation with:
```
npm install twbs/rfs#min-function
```

Docs: https://github.com/twbs/rfs/tree/min-function

Planning to release this on npm as an alpha in the comming days/ weeks. Descided to make an alpha release since the support is still not big enough

**Comment by Ponant** [comment]
Hi @MartijnCuppens , any issue in having this rolled out in main? The min seems supported in most browsers and works great and it shrinkens the css.

**Comment by aaronstezycki** [comment]
Could also adopt `clamp()` by pushing 3 values into the mixin. This would allow a 'stop' value so font sizes don't grow infinitely.
example output: 
```
font-size: clamp(0.9rem, 1vw + 1rem, 2.2rem);
```

**Comment by Galebra** [comment]
In version 10.0.0-alpha.0 I had for `rfs(2.5rem) ` the result

`h1 {
  font-size: min(2.5rem, calc(1.375rem + 1.5vw));
}`

with the known issues about the division warnings.

But now I am getting only the `calc` with an additional media query.
Is switching back to alpha.0 the only way to have the min as per this post? min is very well supported to my taste.

**Comment by Galebra** [comment]
Here is a loosely worked out function which does the job with version 10.0.0

````scss
@use "../../node_modules/rfs/scss" as rfs;

/*
    Adapted helper inspired from 10.0.0-alpha.0 version which uses min instead of media queries
*/
@function rfs-value-min($value) {
    $rfs-val: rfs.rfs-value($value);
    $rfs-fluid-val: rfs.rfs-fluid-value($value);

    @if $rfs-val == $rfs-fluid-val {
        @return $rfs-val;
    }
    @return min($rfs-val, $rfs-fluid-val);
}
````

Usage

````scss
h1 {
    font-size: rfs-value-min(2.5rem);
}

h5 {
    font-size: rfs-value-min(1.25rem);
}
````

Output

````css
h1 {
  font-size: min(2.5rem, calc(1.375rem + 1.5vw));
}

h5 {
  font-size: 1.25rem;
}
````
