### ISSUE TITLE
Scaling other properties than font-size

### ISSUE THREAD

**Issue by Ahrengot** [twbs/rfs#118]
This is more of a general question, but my usual approach to scaling websites is setting a font size in pixels on the html element, setting font-size to 1rem on body and then scaling the html elements font size on larger screens. eg.:

```css
html {
  font-size: 14px;
}

@media (min-width: 980px) {
   html {
    font-size: 16px;
   }
}

body {
  font-size: 1rem;
}
```

Then, with this configuration in place, i define my margins, paddings etc. with rem units so everything scales nicely with the global font size. See this example for instance: https://codepen.io/Ahrengot/pen/KExwVv

I like the fluid font sizing this tool provides, rather than the sudden jumps I get from my current solution, but I can't use this tool for anything outside of the `font-size` css property, can I?

I'd really rather not go back to a place where I need to manually update all of the paddings, margins etc when my font sizes change, but I might have overlooked something in the documentation.

Any input or suggestions are highly appreciated!
