### ISSUE TITLE
Overwriting $rfs-breakpoint in SCSS version is not overwriting the breakpoint correctly

### ISSUE THREAD

**Issue by kimchristiansen** [twbs/rfs#163]
First of all, I would like to say thank you for the awesome resizing engine!

If i overwrite $rfs-breakpoint in my _constants.scss like this:
`$rfs-breakpoint: 1504;`
the media query is still at the default 1200px but the calculation seems to be based on 1504px. The font-size jumps at 1200px viewport width. 
If i write 1504px, the scss compiler is throwing the following error:
`Error: 2.99202/px isn't a valid CSS value ... $variable-width: #{$value-diff * 100 / $rfs-breakpoint}#{$variable`

Changing the $rfs-breakpoint directly in the scss.scss file is working fine.

**Comment by MartijnCuppens** [comment]
> First of all, I would like to say thank you for the awesome resizing engine!

Thanks ❤️

---

You're probably loading you're configuration after you're including the mixin. You'll need to use it like:

```scss
// First define your config:
$rfs-breakpoint: 1504;

// Then include the mixin:
@import "path/to/rfs/scss";

// Then use it:
.title {
  @include font-size(40px);
}
```

Does this help?
