### ISSUE TITLE
Changing $rfs-rem-value doesn't show any effect

### ISSUE THREAD

**Issue by JeromeDeLeon** [twbs/rfs#164]
I tried to change the value of `$rfs-rem-value` but `1rem` is still equal to `16px` but what I want is to change the value of `1rem` to `13px`.

**Comment by MartijnCuppens** [comment]
Hi @JeromeDeLeon,

Make sure sure to define `$rfs-rem-value` before importing the mixin, this will probably solve your issue.

**Comment by JeromeDeLeon** [comment]
I used BS4.3 and I found out that it uses rfs under the hood but changing it doesn't trigger any effect.

```sass
$rfs-rem-value: 13;

@import "/path/to/bootstrap"
```

Did I do anything wrong? I found similar issue and followed it by changing the `font-size` in HTML to atleast `88%`.

**Comment by JeromeDeLeon** [comment]
#102

**Comment by MartijnCuppens** [comment]
`$rfs-rem-value` is only used in the calculations to convert from `px` to `rem` or the other way around.

Because all font-sizes in Bootstrap are passed in `rem` to the mixin, you won't really notice any difference.

However if you use for example `@include font-size(24px)` in your custom css, you'll notice that the font size is still rendered in `rem`, but the calculations are based on a multiplier of 13 (for your case) so that the font size is still 24px for larger viewports.

So codewise:
In the first example we don't adjust `$rfs-rem-value`:
- `64px` won't render as `64px` for large viewports, but will rescale
- The calculations for the responsive part will be slightly incorrect, you'll notice a small font size bump when you resize around the `$rfs-breakpoint` (1200px)
- https://codepen.io/MartijnCuppens/pen/eYOoxRp?editors=1100

```scss
// Use default config
@import "path/to/rfs.scss";

html {
  font-size: 81.25%; // 13/16
}

.title {
  // This font-size will be 52px (81.25% of 64px) for larger viewports and will rescale on smaller screens: 
  @include font-size(64px);
}

.title-2 {
  // This font-size will be 52px (81.25% of 64px) for larger viewports and will rescale on smaller screens:
  @include font-size(4rem);
}
```

In the second example we change `$rfs-rem-value`:
- `64px` will render as `64px` for large viewports
- We won't have the font-size bump explained above.
- Demo: https://codepen.io/MartijnCuppens/pen/ExYJrmy?editors=1100 

```scss
$rfs-rem-value: 13;

@import "path/to/rfs.scss";

html {
  font-size: 81.25%; // 13/16
}

.title {
  // This font-size will be 64px for larger viewports and will rescale on smaller screens: 
  @include font-size(64px);
}

.title-2 {
  // This font-size will be 52px (81.25% of 64px) for larger viewports and will rescale on smaller screens:
  @include font-size(4rem);
}
```

It can be quite hard to understand all this, I had to double check all this when I  was typing this comment, but in short:
- If you change the font size of `html`, you should change `$rfs-rem-value` accordingly for the correct responsive calculations
- You'll only notice a difference for large viewports if the font-sizes are called in `px`. Bootstrap has set all there font sizes in `rem`, so you probably won't spot the difference in that case.
