### ISSUE TITLE
padding-bottom mixin is using font-size property?

### ISSUE THREAD

**Issue by artur-stepien** [twbs/rfs#166]
I got a strange issue. Here is the SCSS I'm using:
```scss

.custom {
    &.jumbotron {
        h2 {
            @include font-size(4.8rem);
            color:$primary;
            font-weight:700;
            div+div {
                font-weight:500;
            }
            @include padding-bottom(5.1rem);
        }
    }
}

```

The result CSS checked in Browser Inspector is as follows:
```css
.custom.jumbotron h2 {
    font-size: 4.8rem;
    color: 
    #2e3192;
    font-weight: 700;
    font-size: 5.1rem !important;
}
```
Whats going on. Am I missing something? Same happens when I'm using `rfs()` mixin. The rfs version is 9.0.0
