### ISSUE TITLE
Other shorthand mixins only build font-size

### ISSUE THREAD

**Issue by beedaan** [twbs/rfs#184]
I'm using version 9.0.2 and was trying out some of the other shorthand mixins.  I noticed that they weren't working for me and upon further inspection, I found they were just compiling more font-size styles.

Src
```sass
.custom_class {
  @include font-size(4rem);
}
```

Compiled
```css
.custom_class {
  font-size: 4rem; }
  @media (max-width: 1200px) {
    .custom_class {
      font-size: calc(1.525rem + 3.3vw) ; } }
```

That works as expected.  Below is the problem I noticed

Src
```sass
.custom_class {
  @include font-size(4rem);
  @include padding-top(6rem);
}
```

Compiled
```css
.custom_class {
  font-size: 4rem;
  font-size: 6rem !important; }
  @media (max-width: 1200px) {
    .custom_class {
      font-size: calc(1.525rem + 3.3vw) ; } }
  @media (max-width: 1200px) {
    .custom_class {
      font-size: calc(1.725rem + 5.7vw)  !important; } }
```

Notice how the padding entry is actually just another font-size entry.

**Comment by MartijnCuppens** [comment]
That's the downside of using Sass mixins, they all generate their own mixin. However, if you use a css minifier like cssnano, these media queries are again combined (you can test this with https://cssnano.co/playground/)

**Comment by beedaan** [comment]
I don't mind the separate media queries.  The problem is that the padding is not changed.  This is what I would like to have

```css

.custom_class {
  font-size: 4rem;
  padding-top: 6rem !important; }
  @media (max-width: 1200px) {
    .custom_class {
      font-size: calc(1.525rem + 3.3vw) ; } }
  @media (max-width: 1200px) {
    .custom_class {
      padding-top: calc(1.725rem + 5.7vw)  !important; } }
```
