### ISSUE TITLE
Weird units after calculation

### ISSUE THREAD

**Issue by B-Prod** [twbs/rfs#247]
It seems that there is a weird case, when combining some rules. The project is based on bootstrap, with RFS. All seems to work properly, except one rule that gives a very strange result:
```scss
h1,
.h1 {
  @include media-breakpoint-up(xl) {
    letter-spacing: -.08rem;
  }

  &.small {
    @include font-size(2.5rem);
    font-weight: bold;

    @include media-breakpoint-up(xl) {
      letter-spacing: 0;
    }
  }
}
```

The compiled CSS is the following:
```scss
@media (max-width: 1200px) {
  h1.small, .h1.small {
      font-size: calc(0.2125remrem + 1.8remvw);
  }
}
```

The HTML code is the following:
```html
<h2 class="h1 small">My title</h2>
```

This is very strange, as the other calculations elsewhere work as expected...

Do you see a reason why this occurs?
