### ISSUE TITLE
Any way to use css variables?

### ISSUE THREAD

**Issue by SvenBudak** [twbs/rfs#311]
On my current project i am forced to use css variables instead of scss variables.
But i was not a ble to make it in this way work: `@include font-size(var(--h6-font-size));`
Someone think it will be possible to use css vars any time?

**Comment by MartijnCuppens** [comment]
Hi @SvenBudak,

In `v9`, you could do:
```scss
:root {
  @include rfs(4rem, --h6-font-size);
}

.title {
  font-size: var(--h6-font-size);
}
```
Which generates
```css
:root {
  --h6-font-size: calc(1.525rem + 3.3vw);
}

@media (min-width: 1200px) {
  :root {
    --h6-font-size: 4rem;
  }
}

.title {
  font-size: var(--h6-font-size);
}
```

In `v10`, you can do this:
```scss
:root {
  --h6-font-size: rfs(4rem);
}

.title {
  font-size: var(--h6-font-size);
}
```
Which generates
```css
:root {
  --h6-font-size: min(4rem, calc(1.525rem + 3.3vw));
}

.title {
  font-size: var(--h6-font-size);
}
```

**Comment by salunet** [comment]
Is this also possible with LESS ?

**Comment by SvenBudak** [comment]
@MartijnCuppens I will check this in next days. sry for late response.

**Comment by MartijnCuppens** [comment]
@salunet, of course:
```less
:root {
  .rfs(4rem, --h6-font-size)
}

.title {
  font-size: var(--h6-font-size);
}
```
