### ISSUE TITLE
using rfs() in SCSS with PostCSS syntax doesnt work 

### ISSUE THREAD

**Issue by issam-seghir** [twbs/rfs#461]
I'm using postcss , with sass (scss syntax) , and i want to use rfs() in postcss syntax like this : 

- `style.scss` file
```scss
:--heading {
	font-size: rfs(4rem);
	...
}
}
```

i'm using `vite ` and when i run **build script** the converted css file look like this : 

- `index.css`

```css
:is(h1, h2, h3, h4, h5, h6) {
  font-size: rfs(4rem); /* not converted to rem 💢*/
  ...
}
```

![image](https://github.com/twbs/rfs/assets/74573675/b599fee0-63d5-4fe1-a9e4-9efb896a31e6)
